CREATE TABLE `Drive Disc leveling` (
    `ID` INT PRIMARY KEY,
    `L_HP` INT DEFAULT 0,
    `L_ATK` INT DEFAULT 0,
    `L_DEF` INT DEFAULT 0,
    `L_%HP` INT DEFAULT 0,
    `L_%ATK` INT DEFAULT 0,
    `L_%DEF` INT DEFAULT 0,
    `L_AP` INT DEFAULT 0,
    `L_PEN` INT DEFAULT 0,
    `L_Crit Rate` INT DEFAULT 0,
    `L_Crit DMG` INT DEFAULT 0,
    `Added substat` VARCHAR(20) DEFAULT 'None',
    `CreateDate` DATE DEFAULT (CURRENT_DATE),
    `LastAdded` DATE DEFAULT (CURRENT_DATE),
    FOREIGN KEY (`ID`) REFERENCES `Drive Disc`(`ID`) ON DELETE CASCADE
);
